# Generated by Django 3.0.7 on 2020-06-21 00:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DB', 'DEBIT'), ('CR', 'CREDIT')], default='DB', max_length=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 0, 54, 25, 224091, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 0, 54, 25, 224091, tzinfo=utc)),
        ),
    ]
