# Generated by Django 3.0.7 on 2020-06-22 23:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20200623_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 23, 1, 17, 513569, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('CR', 'CREDIT'), ('DB', 'DEBIT')], default='DB', max_length=2),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 23, 1, 17, 513569, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='total_amount',
            field=models.FloatField(),
        ),
    ]
